In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('cancer.csv')

In [4]:
df.head()

id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0  1000025                5               1                1              1   
1  1002945                5               4                4              5   
2  1015425                3               1                1              1   
3  1016277                6               8                8              1   
4  1017023                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                       2           1            3              1        1   
1                       7          10            3              2        1   
2                       2           2            3              1        1   
3                       3           4            3              7        1   
4                       2           1            3              1        1   

   classes  
0        0  
1        0  
2        0  
3        0  
4        0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   id                      699 non-null    int64 
 1   clump_thickness         699 non-null    int64 
 2   unif_cell_size          699 non-null    int64 
 3   unif_cell_shape         699 non-null    int64 
 4   marg_adhesion           699 non-null    int64 
 5   single_epith_cell_size  699 non-null    int64 
 6   bare_nuclei             699 non-null    object
 7   bland_chrom             699 non-null    int64 
 8   norm_nucleoli           699 non-null    int64 
 9   mitoses                 699 non-null    int64 
 10  classes                 699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [6]:
df.describe()

id  clump_thickness  unif_cell_size  unif_cell_shape  \
count  6.990000e+02       699.000000      699.000000       699.000000   
mean   1.071704e+06         4.417740        3.134478         3.207439   
std    6.170957e+05         2.815741        3.051459         2.971913   
min    6.163400e+04         1.000000        1.000000         1.000000   
25%    8.706885e+05         2.000000        1.000000         1.000000   
50%    1.171710e+06         4.000000        1.000000         1.000000   
75%    1.238298e+06         6.000000        5.000000         5.000000   
max    1.345435e+07        10.000000       10.000000        10.000000   

       marg_adhesion  single_epith_cell_size  bland_chrom  norm_nucleoli  \
count     699.000000              699.000000   699.000000     699.000000   
mean        2.806867                3.216023     3.437768       2.866953   
std         2.855379                2.214300     2.438364       3.053634   
min         1.000000                1.000000     1.000000       1.000000   
25%         1.000000                2.000000     2.000000       1.000000   
50%         1.000000                2.000000     3.000000       1.000000   
75%         4.000000                4.000000     5.000000       4.000000   
max        10.000000               10.000000    10.000000      10.000000   

          mitoses     classes  
count  699.000000  699.000000  
mean     1.589413    0.344778  
std      1.715078    0.475636  
min      1.000000    0.000000  
25%      1.000000    0.000000  
50%      1.000000    0.000000  
75%      1.000000    1.000000  
max     10.000000    1.000000

In [4]:
df.replace('?',-99999,inplace=True)

In [5]:
df.drop(['id'],1,inplace=True)

In [6]:
df.head()

clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0                5               1                1              1   
1                5               4                4              5   
2                3               1                1              1   
3                6               8                8              1   
4                4               1                1              3   

   single_epith_cell_size bare_nuclei  bland_chrom  norm_nucleoli  mitoses  \
0                       2           1            3              1        1   
1                       7          10            3              2        1   
2                       2           2            3              1        1   
3                       3           4            3              7        1   
4                       2           1            3              1        1   

   classes  
0        0  
1        0  
2        0  
3        0  
4        0

In [7]:
X=np.array(df.drop(['classes'],1))
y=np.array(df['classes'])

In [8]:
X

array([[5, 1, 1, ..., 3, 1, 1],
       [5, 4, 4, ..., 3, 2, 1],
       [3, 1, 1, ..., 3, 1, 1],
       ...,
       [5, 10, 10, ..., 8, 10, 2],
       [4, 8, 6, ..., 10, 6, 1],
       [4, 8, 8, ..., 10, 4, 1]], dtype=object)

In [9]:
y

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train

array([[-1.19480731, -0.70594093, -0.74391107, ..., -0.17105851,
        -0.60754169, -0.35584471],
       [-0.49527767, -0.70594093, -0.74391107, ..., -0.58796391,
        -0.60754169, -0.35584471],
       [ 0.20425198, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.60754169, -0.35584471],
       ...,
       [-0.14551285,  1.61222498,  0.93052793, ...,  1.49656308,
        -0.60754169, -0.35584471],
       [-0.84504249, -0.70594093, -0.74391107, ..., -0.58796391,
        -0.60754169, -0.35584471],
       [ 0.20425198,  2.27455809,  2.27007913, ...,  2.74727927,
         1.0100998 ,  1.77515675]])

In [13]:
X_test

array([[-0.14551285, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.60754169, -0.35584471],
       [-0.84504249, -0.70594093, -0.74391107, ..., -0.17105851,
        -0.60754169, -0.35584471],
       [ 1.95307608,  2.27455809,  0.93052793, ...,  0.24584688,
         0.03951491,  0.17690566],
       ...,
       [-0.14551285, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.28401339, -0.35584471],
       [-0.49527767, -0.70594093, -0.74391107, ..., -0.58796391,
        -0.60754169, -0.35584471],
       [-0.49527767, -0.70594093, -0.74391107, ..., -1.00486931,
        -0.60754169, -0.35584471]])

In [14]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)
explained_variance=pca.explained_variance_ratio_

In [15]:
X_train

array([[-1.7507631 , -0.13706882],
       [-1.6798227 , -0.15154471],
       [-1.6088823 , -0.1660206 ],
       ...,
       [ 1.34855718,  0.01536871],
       [-1.78983662, -0.15713299],
       [ 5.19752268, -0.04178352]])

In [16]:
X_test

array([[-1.58582877e+00, -8.11540681e-01],
       [-1.46012087e+00, -7.55803438e-01],
       [ 2.14155665e+00, -3.40757018e-02],
       [ 2.59176002e+00,  2.07740074e-01],
       [-1.22129906e+00, -7.12546156e-01],
       [-1.41489186e+00, -7.75200538e-01],
       [-1.53656186e+00, -7.72687931e-01],
       [ 2.40251594e+00,  7.54517325e-02],
       [-3.43645470e+00,  7.72182064e+00],
       [ 4.05965033e+00,  4.35368619e-01],
       [-1.60762070e+00, -7.90836264e-01],
       [ 2.92174475e+00,  1.30877046e-01],
       [ 7.12822046e-01,  8.69077857e+00],
       [-1.20220609e+00, -7.33008338e-01],
       [-2.23158182e+00,  7.97351537e+00],
       [-1.69383940e+00, -8.20352237e-01],
       [-3.69867743e+00,  7.67708602e+00],
       [-1.52297482e+00, -7.83672060e-01],
       [ 2.86206111e+00,  1.41741501e-01],
       [ 2.94071631e+00,  2.05669727e-01],
       [-1.47766304e+00, -7.31043583e-01],
       [ 3.23745455e+00,  2.98566211e-01],
       [ 3.88203962e+00,  4.26695314e-01],
       [-1.

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = []
for i in range(1,21):
           
    classifier = KNeighborsClassifier(n_neighbors=i)
    trained_model=classifier.fit(X_train,y_train)
    trained_model.fit(X_train,y_train )

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
cm_KNN = confusion_matrix(y_test, y_pred)
print(cm_KNN)
print("Accuracy score of train KNN")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)
    
print("Accuracy score of test KNN")
print(accuracy_score(y_test, y_pred)*100)
    
knn.append(accuracy_score(y_test, y_pred)*100)

[[111   5]
 [  1  58]]
Accuracy score of train KNN
96.94656488549617
Accuracy score of test KNN
96.57142857142857


In [21]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)

trained_model=classifier.fit(X_train,y_train)
trained_model.fit(X_train,y_train )

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [22]:
y_pred = classifier.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix
cm_SVM = confusion_matrix(y_test, y_pred)
print(cm_SVM)
print("Accuracy score of train SVM")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)

print("Accuracy score of test SVM")
print(accuracy_score(y_test, y_pred)*100)

[[111   5]
 [  1  58]]
Accuracy score of train SVM
95.99236641221374
Accuracy score of test SVM
96.57142857142857
